INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 7, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJA', 'OC2', '2019-03-04', 8, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-04', 1, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-04', 2, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-04', 3, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-04', 4, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-04', 5, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-04', 6, 'Test Submission', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
