INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-04', 1, 'Test Submission', '1XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJQ', 'OC2', '2019-03-05', 2, 'Test Submission', '1XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-06', 3, 'Test Submission', '2XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-07', 4, 'Test Submission', '2XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-08', 5, 'Test Submission', '3XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-09', 6, 'Test Submission', '3XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC7', '2019-03-11', 7, 'Test Submission', '4XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC8', '2019-03-12', 8, 'Test Submission', '4XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('AJW', 'OC1', '2019-03-13', 1, 'Test Submission', '5XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RCA', 'OC2', '2019-03-14', 2, 'Test Submission', '5XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('DJB', 'OC3', '2019-03-15', 3, 'Test Submission', 'L6XX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJA', 'OC4', '2019-03-16', 4, 'Test Submission', 'L6XX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('POA', 'OC1', '2019-03-18', 5, 'Test Submission', '1XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('CJQ', 'OC2', '2019-03-19', 6, 'Test Submission', '1XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJB', 'OC3', '2019-03-20', 7, 'Test Submission', '2XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TAD', 'OC4', '2019-03-21', 8, 'Test Submission', '2XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('JHP', 'OC5', '2019-03-22', 1, 'Test Submission', '3XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RFH', 'OC6', '2019-03-23', 2, 'Test Submission', '3XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('TMB', 'OC1', '2019-03-25', 3, 'Test Submission', '4XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RJM', 'OC2', '2019-03-26', 4, 'Test Submission', '4XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');

INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('AJW', 'OC1', '2019-03-27', 5, 'Test Submission', '5XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('RCA', 'OC2', '2019-03-28', 6, 'Test Submission', '5XXX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('DJB', 'OC3', '2019-03-29', 7, 'Test Submission', 'L6XX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
INSERT INTO orders (teacher, room, dateReq, period, description, form, sets, chemical, quantity, allocation, hazards, apparatus, addnotes) VALUES ('MJA', 'OC4', '2019-03-30', 8, 'Test Submission', 'L6XX', 16, 'Hydrochloric Acid', '2dm3', 'Bulk', 'Corrosive', 'Standard Glassware', 'Noting to add');
